1. Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.



In [1]:
import numpy as np


arr = np.array([1, 2, 3, 4, 5, 6], dtype=int)


print("Array:", arr)


print("Boyut sayısı:", arr.ndim)


print("Eleman sayısı:", arr.size)


print("Şekil:", arr.shape)


print("Veri tipi:", arr.dtype)


Array: [1 2 3 4 5 6]
Boyut sayısı: 1
Eleman sayısı: 6
Şekil: (6,)
Veri tipi: int64


2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım.

İki boyutlu array:
[[1,2,6,7],
[4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
[[8,6,20],[14,3,9]]]



In [ ]:
import numpy as np


arr2d = np.array([[1,2,6,7],
                  [4,3,9,5]])

print("İki Boyutlu Array:")
print(arr2d)
print("Boyut (ndim):", arr2d.ndim)  
print("Shape (satır, sütun):", arr2d.shape) 
print("Eleman Sayısı (size):", arr2d.size)    
print()


arr3d = np.array([[[7,5,14],[21,8,11]],
                  [[8,6,20],[14,3,9]]])

print("Üç Boyutlu Array:")
print(arr3d)
print("Boyut (ndim):", arr3d.ndim)   
print("Shape:", arr3d.shape)         
print("Eleman Sayısı (size):", arr3d.size)


3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım.

İki boyutlu arraydaki 2 elemanına ulaşalım.

İki boyutlu arraydaki 7 elemanına ulaşalım.

Üç boyutlu arraydaki 9 elemanına ulaşalım.

Üç boyutlu arraydaki 5 elemanına ulaşalım.



In [ ]:
import numpy as np


arr2d = np.array([[1,2,6,7],
                  [4,3,9,5]])


arr3d = np.array([[[7,5,14],[21,8,11]],
                  [[8,6,20],[14,3,9]]])



print("İki Boyutlu Array 2 elemanı:", arr2d[0,1])  
print("İki Boyutlu Array 7 elemanı:", arr2d[0,3]) 


print("Üç Boyutlu Array 9 elemanı:", arr3d[1,1,2])  
print("Üç Boyutlu Array 5 elemanı:", arr3d[0,0,1])  


4. Arrayler üzerinde slicing işlemi uygulayalım.

İki boyutlu arraydaki 2,6 elemanlarına ulaşalım.

İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım.

Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım.

Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım.



In [ ]:

print("İki Boyutlu Array 2,6 elemanları:", arr2d[0,1:3])  
print("İki Boyutlu Array 3,9,5 elemanları:", arr2d[1,1:4]) 


print("Üç Boyutlu Array 21,8,11 elemanları:", arr3d[0,1,:]) 
print("Üç Boyutlu Array 6,20 elemanları:", arr3d[1,0,1:3])   


5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [2]:



arr_sifir = np.zeros((5,3), dtype=int)


arr_bir = np.ones((5,3), dtype=int)

print("Sıfırlardan oluşan array:\n", arr_sifir)
print("Birlerden oluşan array:\n", arr_bir)


satir_birlestirme = np.vstack((arr_sifir, arr_bir))
print("\nSatır bazında birleştirme (vstack):\n", satir_birlestirme)


sutun_birlestirme = np.hstack((arr_sifir, arr_bir))
print("\nSütun bazında birleştirme (hstack):\n", sutun_birlestirme)


Sıfırlardan oluşan array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Birlerden oluşan array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Satır bazında birleştirme (vstack):
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Sütun bazında birleştirme (hstack):
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
